<?php
/**
 *
 * @copyright Copyright (c) 2013-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest\Service;

use NpPage\Service\ConfigFileResolverFactory;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 22:51:40.
 */
class ConfigFileResolverFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFileResolverFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigFileResolverFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpPage\Service\ConfigFileResolverFactory::createService
     */
    public function testCreateService()
    {
        $serviceConfig = array(
            'np-page' => array(
                'config_resolver' => array(
                    'map' => array(),
                    'path_stack' => array(),
                ),
            ),
        );
        $class = 'NpPage\\Config\\ConfigFileResolver';
        $serviceLocator = new ServiceManager;
        $serviceLocator->setService('Config', $serviceConfig);


        $res = $this->object->createService($serviceLocator);
        $this->assertInstanceOf($class, $res);
    }
}
