<?php
/**
 *
 * @copyright Copyright (c) 2013-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest\Service;

use Flower\Test\TestTool;
use NpPage\Service\ConfigLoaderFileFactory;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 22:51:46.
 */
class ConfigLoaderFileFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigLoaderFileFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigLoaderFileFactory;
    }

    /**
     * @covers NpPage\Service\ConfigLoaderFileFactory::createService
     */
    public function testCreateService()
    {
        $serviceConfig = array(
            'np-page' => array(
                'config_resolver_name' => 'foo',
            ),
        );
        $class = TestTool::getPropertyValue($this->object, 'class');
        $resolver = $this->getMock('NpPage\\Config\\ConfigResolverInterface');
        $serviceLocator = new ServiceManager;
        $serviceLocator->setService('Config', $serviceConfig);
        $serviceLocator->setService('foo', $resolver);

        $res = $this->object->createService($serviceLocator);
        $this->assertInstanceOf($class, $res);
        $this->assertSame($resolver, $res->getResolver());
    }
}
