<?php
/*
 *
 *
 * @copyright Copyright (c) 2014-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest\Service;

use NpPage\Service\ServiceFactory;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 14:09:40.
 */
class ServiceFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServiceFactory
     */
    protected $object;

    protected $serviceLocator;

    protected $serviceConfig;

    protected $configArray =  array();

    protected $repository;

    protected function setUp()
    {
        $this->object = new ServiceFactory;
        $this->configArray = array();
        $this->repository = $this->getMock('NpPage\\Repository');
        $this->serviceLocator = new ServiceManager;
        $this->serviceLocator->setService('NpPage_BlockRepository', $this->repository);
    }

    protected function tearDown()
    {

    }

    /**
     * @covers NpPage\Service\ServiceFactory::createService
     */
    public function testCreateService()
    {
        $this->configArray = array(
            'repository_service_name' => 'NpPage_BlockRepository',
        );
        $this->serviceLocator->setService('Config', array('np-page' => $this->configArray));
        $res = $this->object->createService($this->serviceLocator);
        $this->assertInstanceOf('NpPage\\ServiceInterface', $res);
        $this->assertSame($this->repository, $res->getRepository());
    }
}
