<?php
/**
 *
 * @copyright Copyright (c) 2013-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest\Block;

use NpPage\Block\Page;
use NpPage\Service;
use Zend\Mvc\MvcEvent;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-15 at 19:25:20.
 */
class PageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Page
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Page;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @deprecated PageBuilderに依存しているだけなので不適切
     * @covers NpPage\Block\Page::build
     */
    public function testBuild()
    {
        $sl = new ServiceManager;
        $event = new MvcEvent;
        $viewManager = $this->getMock('Zend\\Mvc\\View\\Http\\ViewManager');
        $viewManager->expects($this->once())
                ->method('getLayoutTemplate')
                ->will($this->returnValue('foo'));
        $application = $this->getMockBuilder('Zend\\Mvc\\Application')
                ->disableOriginalConstructor()->getMock();
        $application->expects($this->once())
                ->method('getMvcEvent')
                ->will($this->returnValue($event));
        $sl->setService('view_manager', $viewManager);
        $sl->setService('application', $application);

        $initializer = $this->getMock('NpPage\\BlockInitializer');
        $initializer->expects($this->once())
                ->method('getServiceLocator')
                ->will($this->returnValue($sl));
        $this->object->init($initializer);
        $this->object->build();

        $this->assertTrue($this->object->getViewModel()->terminate());
        $this->assertEquals('foo', $this->object->getViewModel()->getTemplate());
    }
}
