<?php
/*
 *
 *
 * @copyright Copyright (c) 2014-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest\Config;

use NpPage\Config\ConfigFileResolver;
use Flower\Test\TestTool;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 22:16:54.
 */
class ConfigFileResolverTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFileResolver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigFileResolver;
    }

    public function testAttach()
    {
        $resolver = $this->getMock('Zend\\View\\Resolver\\ResolverInterface');
        $this->object->attach($resolver);
        $queue = TestTool::getPropertyValue($this->object, 'queue');
        $this->assertFalse($queue->isEmpty());
    }

    public function testResolve()
    {
        $name = 'foo';
        $result = 'bar';
        $resolver = $this->getMock('Zend\\View\\Resolver\\ResolverInterface');
        $resolver->expects($this->once())
                ->method('resolve')
                ->with($this->equalTo($name))
                ->will($this->returnValue($result));
        $this->object->attach($resolver);
        $res = $this->object->resolve($name);
        $this->assertEquals($result, $res);
    }
}
