<?php
/**
 *
 * @copyright Copyright (c) 2013-2014 KipsProduction (http://www.kips.gr.jp)
 * @license   http://www.kips.gr.jp/newbsd/LICENSE.txt New BSD License
 */

namespace NpPageTest;

use Flower\Test\TestTool;
use NpPage\ServiceSubscriber;
use Zend\EventManager\EventManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 19:53:52.
 */
class ServiceSubscriberTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServiceSubscriber
     */
    protected $object;

    /**
     *
     * @var \NpPage\Service
     */
    protected $service;

    protected function setUp()
    {
        $this->service = $this->getMock('NpPage\\Service');
        $this->object = new ServiceSubscriber($this->service);
    }

    public function testConstruct()
    {
        $this->assertSame($this->service, TestTool::getPropertyValue($this->object, 'service'));
    }

    /**
     * @covers NpPage\ServiceSubscriber::attach
     */
    public function testAttach()
    {
        $eventManager = new EventManager;
        $this->object->attach($eventManager);
        $listeners = TestTool::getPropertyValue($this->object, 'listeners');
        $listener = array_shift($listeners);
        $callback = TestTool::getPropertyValue($listener, 'callback');
        $this->assertSame($this->service, $callback[0]);
        $this->assertEquals('onRoute', $callback[1]);
    }

    /**
     * @covers NpPage\ServiceSubscriber::detach
     */
    public function testDetach()
    {
        $eventManager = new EventManager;
        $this->object->attach($eventManager);
        $this->object->detach($eventManager);
        $this->assertEmpty(TestTool::getPropertyValue($this->object, 'listeners'));
    }
}
